# Generated by Django 5.0 on 2023-12-26 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_alter_itemcarrinho_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
